const REGIMENT_DATA = {
  factions: [
    {
      id: "emp_all",
      name: "Galactic Empire",
      type: "Major",
      command_value: "6+",
      leaders: [
        {
          id: "ldr_vader",
          name: "Darth Vader",
          cost: 45,
          restriction_text: "Must be attached to an Infantry unit.",
          requires_class: "Infantry",
          requires_subclass: null,
          ability: "Placeholder text."
        },
        {
          id: "ldr_tarkin",
          name: "Grand Moff Tarkin",
          cost: 30,
          restriction_text: "None.",
          requires_class: null,
          requires_subclass: null,
          ability: "Placeholder text."
        },
        {
          id: "ldr_veers",
          name: "General Veers",
          cost: 40,
          restriction_text: "Must be attached to a Walker unit.",
          requires_class: null,
          requires_subclass: "Walker",
          ability: "Placeholder text."
        }
      ],
      units: [
        { 
          id: "emp_stm", 
          name: "Stormtroopers", 
          unit_size: 3,
          cost: 50, 
          min_pct: 15, 
          max_pct: null, 
          class: "Infantry",
          subclass: null,
          mv: 6, mv_max: null,
          atk_ranged: 2, atk_melee: 3,
          rng_short: 8, rng_long: 12,
          wnd: 3, sv: "5+",
          keywords: [] 
        },
        { 
          id: "emp_dth", 
          name: "Death Troopers", 
          unit_size: 2,
          cost: 75, 
          min_pct: 0, 
          max_pct: 15, 
          class: "Infantry",
          subclass: null,
          mv: 6, mv_max: null,
          atk_ranged: 3, atk_melee: 3,
          rng_short: 10, rng_long: 12,
          wnd: 3, sv: "5+",
          keywords: ["Fearless"] 
        },
        { 
          id: "emp_hvy", 
          name: "Heavy Weapons Teams", 
          unit_size: 2,
          cost: 90, 
          min_pct: 0, 
          max_pct: 40, 
          class: "Infantry",
          subclass: null,
          mv: 4, mv_max: null,
          atk_ranged: 4, atk_melee: 2,
          rng_short: 12, rng_long: 20,
          wnd: 3, sv: "5+",
          keywords: ["Anti-Armor"] 
        },
        { 
          id: "emp_trp", 
          name: "Imperial Transport", 
          unit_size: 1,
          cost: 100, 
          min_pct: 0, 
          max_pct: 60, 
          class: "Vehicle",
          subclass: "Hover",
          mv: 8, mv_max: null,
          atk_ranged: 2, atk_melee: 2,
          rng_short: 8, rng_long: 12,
          wnd: 2, sv: "4+",
          keywords: ["Transport"] 
        },
        { 
          id: "emp_ats", 
          name: "AT-ST", 
          unit_size: 2,
          cost: 150, 
          min_pct: 0, 
          max_pct: 75, 
          class: "Vehicle",
          subclass: "Walker",
          mv: 8, mv_max: null,
          atk_ranged: 3, atk_melee: 3,
          rng_short: 10, rng_long: 14,
          wnd: 3, sv: "4+",
          keywords: [] 
        },
        { 
          id: "emp_tbo", 
          name: "Turbolaser Tower", 
          unit_size: 1,
          cost: 110, 
          min_pct: 0, 
          max_pct: 35, 
          class: "Emplacement",
          subclass: null,
          mv: 0, mv_max: null,
          atk_ranged: 6, atk_melee: null,
          rng_short: 14, rng_long: 24,
          wnd: 3, sv: "4+",
          keywords: ["Anti-Armor"] 
        },
        { 
          id: "emp_ata", 
          name: "AT-AT", 
          unit_size: 1,
          cost: 300, 
          min_pct: 0, 
          max_pct: 60, 
          class: "Titan",
          subclass: "Walker",
          mv: 6, mv_max: null,
          atk_ranged: 5, atk_melee: 6,
          rng_short: 12, rng_long: 24,
          wnd: 6, sv: "3+",
          keywords: ["Anti-Armor", "Heavy Armor", "Towering", "Transport"] 
        }
      ]
    },
    {
      id: "reb_all",
      name: "Rebel Alliance",
      type: "Major",
      units: [
        { 
          id: "reb_trp", 
          name: "Rebel Troopers", 
          unit_size: 3,
          cost: 40, 
          min_pct: 15, 
          max_pct: null, 
          class: "Infantry",
          subclass: null,
          mv: 6, mv_max: null,
          atk_ranged: 2, atk_melee: 3,
          rng_short: 8, rng_long: 12,
          wnd: 3, sv: "6+",
          keywords: [] 
        },
        { 
          id: "reb_pth", 
          name: "Rebel Pathfinders", 
          unit_size: 2,
          cost: 75, 
          min_pct: 0, 
          max_pct: 30, 
          class: "Infantry",
          subclass: null,
          mv: 6, mv_max: null,
          atk_ranged: 2, atk_melee: 3,
          rng_short: 10, rng_long: 12,
          wnd: 3, sv: "5+",
          keywords: ["Clone"] 
        },
        { 
          id: "reb_tau", 
          name: "Tauntaun Riders", 
          unit_size: 2,
          cost: 90, 
          min_pct: 0, 
          max_pct: 40, 
          class: "Vehicle",
          subclass: "Ground",
          mv: 10, mv_max: null,
          atk_ranged: 2, atk_melee: 2,
          rng_short: 8, rng_long: 12,
          wnd: 2, sv: "5+",
          keywords: [] 
        },
        { 
          id: "reb_aa5", 
          name: "A-A5 Transport", 
          unit_size: 1,
          cost: 100, 
          min_pct: 0, 
          max_pct: 40, 
          class: "Vehicle",
          subclass: "Hover",
          mv: 8, mv_max: null,
          atk_ranged: 2, atk_melee: 2,
          rng_short: 8, rng_long: 12,
          wnd: 2, sv: "4+",
          keywords: ["Transport"] 
        },
        { 
          id: "reb_ptw", 
          name: "P-Tower", 
          unit_size: 1,
          cost: 150, 
          min_pct: 0, 
          max_pct: 60, 
          class: "Emplacement",
          subclass: null,
          mv: 0, mv_max: null,
          atk_ranged: 5, atk_melee: 1,
          rng_short: 14, rng_long: 24,
          wnd: 3, sv: "4+",
          keywords: ["Anti-Armor"] 
        },
        { 
          id: "reb_snw", 
          name: "Snowspeeder", 
          unit_size: 1,
          cost: 110, 
          min_pct: 0, 
          max_pct: 35, 
          class: "Vehicle",
          subclass: "Aerial",
          mv: 4, mv_max: 14,
          atk_ranged: 3, atk_melee: null,
          rng_short: 10, rng_long: 16,
          wnd: 4, sv: "4+",
          keywords: ["Tow-Cable"] 
        }
      ]
    },
    {
      id: "rep_all",
      name: "Galactic Republic",
      type: "Major",
      units: [
        { 
          id: "rep_clone_troopers", 
          name: "Clone Troopers", 
          unit_size: 3,
          cost: 50, 
          min_pct: 15, 
          max_pct: null, 
          class: "Infantry",
          subclass: null,
          mv: 6, mv_max: null,
          atk_ranged: 2, atk_melee: 3,
          rng_short: 8, rng_long: 12,
          wnd: 3, sv: "6+",
          keywords: ["Clone"] 
        },
        { 
          id: "rep_arc_troopers", 
          name: "ARC Troopers", 
          unit_size: 2,
          cost: 100, 
          min_pct: 0, 
          max_pct: 40, 
          class: "Infantry",
          subclass: null,
          mv: 6, mv_max: null,
          atk_ranged: 3, atk_melee: 3,
          rng_short: 10, rng_long: 12,
          wnd: 3, sv: "5+",
          keywords: ["Clone"] 
        },
        { 
          id: "rep_jetpack_troopers", 
          name: "Jetpack Troopers", 
          unit_size: 2,
          cost: 90, 
          min_pct: 0, 
          max_pct: 40, 
          class: "Infantry",
          subclass: null,
          mv: 8, mv_max: null,
          atk_ranged: 2, atk_melee: 3,
          rng_short: 10, rng_long: 14,
          wnd: 3, sv: "6+",
          keywords: ["Clone", "Jetpacks"] 
        },
        { 
          id: "rep_atrt", 
          name: "AT-RT Walkers", 
          unit_size: 2,
          cost: 100, 
          min_pct: 0, 
          max_pct: 60, 
          class: "Vehicle",
          subclass: "Walker",
          mv: 10, mv_max: null,
          atk_ranged: 3, atk_melee: 2,
          rng_short: 8, rng_long: 12,
          wnd: 2, sv: "5+",
          keywords: [] 
        },
        { 
          id: "rep_tx130", 
          name: "TX-130 Tanks", 
          unit_size: 2,
          cost: 150, 
          min_pct: 0, 
          max_pct: 75, 
          class: "Vehicle",
          subclass: "Hover",
          mv: 10, mv_max: null,
          atk_ranged: 4, atk_melee: 1,
          rng_short: 10, rng_long: 14,
          wnd: 3, sv: "4+",
          keywords: ["Anti-Armor"] 
        },
        { 
          id: "rep_av7", 
          name: "AV-7 Cannon", 
          unit_size: 1,
          cost: 125, 
          min_pct: 0, 
          max_pct: 40, 
          class: "Emplacement",
          subclass: null,
          mv: 0, mv_max: null,
          atk_ranged: 5, atk_melee: 1,
          rng_short: 20, rng_long: 26,
          wnd: 5, sv: "4+",
          keywords: ["Artillery", "Anti-Armor"] 
        },
        { 
          id: "rep_laati", 
          name: "LAAT/i Gunship", 
          unit_size: 1,
          cost: 150, 
          min_pct: 0, 
          max_pct: 30, 
          class: "Vehicle",
          subclass: "Aerial",
          mv: 4, mv_max: 14,
          atk_ranged: 3, atk_melee: null,
          rng_short: 10, rng_long: 16,
          wnd: 5, sv: "4+",
          keywords: ["Transport"] 
        },
        { 
          id: "rep_atte", 
          name: "AT-TE", 
          unit_size: 1,
          cost: 250, 
          min_pct: 0, 
          max_pct: 75, 
          class: "Titan",
          subclass: "Walker",
          mv: 6, mv_max: null,
          atk_ranged: 5, atk_melee: 5,
          rng_short: 12, rng_long: 20,
          wnd: 6, sv: "3+",
          keywords: ["Heavy Armor", "Transport"] 
        }
      ]
    },
    {
      id: "sep_all",
      name: "Separatist Alliance",
      type: "Major",
      units: [
        { 
          id: "sep_b1", 
          name: "B1 Battle Droids", 
          unit_size: 4,
          cost: 40, 
          min_pct: 20, 
          max_pct: null, 
          class: "Infantry",
          subclass: null,
          mv: 6, mv_max: null,
          atk_ranged: 2, atk_melee: 2,
          rng_short: 4, rng_long: 10,
          wnd: 3, sv: "-",
          keywords: ["Droid"] 
        },
        { 
          id: "sep_b2", 
          name: "B2 Super Battle Droids", 
          unit_size: 3,
          cost: 65, 
          min_pct: 10, 
          max_pct: 40, 
          class: "Infantry",
          subclass: null,
          mv: 6, mv_max: null,
          atk_ranged: 2, atk_melee: 3,
          rng_short: 8, rng_long: 12,
          wnd: 3, sv: "6+",
          keywords: ["Droid"] 
        },
        { 
          id: "sep_droidekas", 
          name: "Droidekas", 
          unit_size: 2,
          cost: 90, 
          min_pct: 0, 
          max_pct: 40, 
          class: "Infantry",
          subclass: null,
          mv: 8, mv_max: null,
          atk_ranged: 4, atk_melee: 2,
          rng_short: 6, rng_long: 10,
          wnd: 2, sv: "4+",
          keywords: ["Droid"] 
        },
        { 
          id: "sep_j1_cannon", 
          name: "J-1 Proton Cannon", 
          unit_size: 1,
          cost: 125, 
          min_pct: 0, 
          max_pct: 50, 
          class: "Emplacement",
          subclass: null,
          mv: 0, mv_max: null,
          atk_ranged: 5, atk_melee: 1,
          rng_short: 20, rng_long: 26,
          wnd: 5, sv: "4+",
          keywords: ["Artillery", "Anti-Armor"] 
        },
        { 
          id: "sep_aat", 
          name: "AAT Tanks", 
          unit_size: 2,
          cost: 150, 
          min_pct: 0, 
          max_pct: 75, 
          class: "Vehicle",
          subclass: "Hover",
          mv: 8, mv_max: null,
          atk_ranged: 4, atk_melee: 1,
          rng_short: 12, rng_long: 16,
          wnd: 4, sv: "4+",
          keywords: ["Anti-Armor"] 
        },
        { 
          id: "sep_hailfire", 
          name: "Hailfire Tanks", 
          unit_size: 2,
          cost: 150, 
          min_pct: 0, 
          max_pct: 45, 
          class: "Vehicle",
          subclass: "Ground",
          mv: 9, mv_max: null,
          atk_ranged: 4, atk_melee: 2,
          rng_short: 14, rng_long: 18,
          wnd: 3, sv: "5+",
          keywords: ["Anti-Armor"] 
        },
        { 
          id: "sep_hmp", 
          name: "HMP Gunship", 
          unit_size: 1,
          cost: 150, 
          min_pct: 0, 
          max_pct: 30, 
          class: "Vehicle",
          subclass: "Aerial",
          mv: 4, mv_max: 14,
          atk_ranged: 3, atk_melee: null,
          rng_short: 10, rng_long: 16,
          wnd: 4, sv: "4+",
          keywords: ["Transport"] 
        },
        { 
          id: "sep_octuptarra", 
          name: "Octuptarra Magna Tri-Droid", 
          unit_size: 1,
          cost: 250, 
          min_pct: 0, 
          max_pct: 50, 
          class: "Titan",
          subclass: "Walker",
          mv: 6, mv_max: null,
          atk_ranged: 5, atk_melee: 2,
          rng_short: 12, rng_long: 16,
          wnd: 5, sv: "4+",
          keywords: ["Towering", "Omnipresent"] 
        },
        { 
          id: "sep_mtt", 
          name: "MTT", 
          unit_size: 1,
          cost: 200, 
          min_pct: 0, 
          max_pct: 40, 
          class: "Titan",
          subclass: "Hover",
          mv: 10, mv_max: null,
          atk_ranged: 3, atk_melee: 1,
          rng_short: 10, rng_long: 16,
          wnd: 5, sv: "4+",
          keywords: ["Heavy Armor", "Transport"] 
        }
      ]
    },
    {
      id: "gun_all",
      name: "Gungan Grand Army",
      type: "Minor",
      units: []
    }
  ],

  ots: [
    { 
      id: "ots_mortar", 
      name: "Mortar Attack", 
      cost: 20, 
      availability: "4+", 
      template: "Single Card (3.5\" x 2.5\")",
      attack_dice: 3,
      keywords: []
    },
    { 
      id: "ots_strafing", 
      name: "Strafing Run", 
      cost: 35, 
      availability: "5+", 
      template: "Double Card - Long (7\" x 2.5\")",
      attack_dice: 4,
      keywords: ["Anti-Armor"]
    },
    { 
      id: "ots_artillery", 
      name: "Artillery Barrage", 
      cost: 50, 
      availability: "6+", 
      template: "Double Card - Wide (5\" x 3.5\")",
      attack_dice: 6,
      keywords: ["Anti-Armor"]
    },
    { 
      id: "ots_orbital", 
      name: "Orbital Bombardment", 
      cost: 75, 
      availability: "7+", 
      template: "Single Card (3.5\" x 2.5\")",
      attack_dice: 8,
      keywords: ["Anti-Armor"]
    }
  ],

  definitions: {
    "Anti-Armor": "Weapons capable of damaging units with the “Heavy Armor” keyword from the front.",
    "Artillery": "May shoot at targets even if Line of Sight is blocked. Does not suffer the +1 To-Hit penalty for Long Range.",
    "Booma Balls": "When shooting vehicles or units with the “Droid” keyword, after rolling to hit, you may change 1 miss into a hit. May shoot at targets even if Line of Sight is blocked.",
    "Clone": "When this unit would become shaken, roll 1d6. On a result of 5+, it is not shaken.",
    "Droid": "When this unit would become shaken, you may choose to take 1 wound instead.",
    "Fearless": "This unit cannot become Shaken.",
    "Heavy Armor": "Immune to standard fire from the front. All hits from units without the Anti-Armor keyword are automatically saved if received from the front facing. Flanking units without Anti-Armor can only hit on 6+ when shooting.",
    "Jetpacks": "Ignores all terrain movement penalties and can move over enemy units.",
    "Omnipresent": "Cannot be flanked and can shoot from any of its base edges",
    "Tow-Cable": "The unit must declare a charge on a Walker Titan and enter base contact. Ignore normal charge rules. Roll 3 attack dice, hitting on a 2+. The Walker rolls its saves needing a 2+. Any unsaved hits results in the Walker's instant destruction.",
    "Towering": "Can draw Line of Sight over terrain and all other units.",
    "Transport": "This unit may transport one Infantry unit.",
    "Unhindered": "This unit ignores difficult terrain penalties."
  }
};